[workspace]
members = [
    "template-project",
    "libraries/dimdraw",
    "libraries/parts",
    "wood-projects/couch",
    "wood-projects/slab-table",
    "wood-projects/table",
    "sandbox/house",
    "sandbox/rammed-earth",
]
