[package]
name = "table"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"

[dependencies]
scad = "1.0.1"
nalgebra = "*"

[dependencies.parts]
path = "../../libraries/parts/"

[dependencies.dimdraw]
path = "../../libraries/dimdraw/"
