#!/usr/bin/env bash

set -e

if (( $# != 1 ))
then
  echo "usage: $0 <rust-executable>"
  exit 1
fi

EXEC_FILE="$1"
#OPENSCAD_ARGS="${@:2}"

# run the Rust executable, expects it to output the scad filename
# as the first token in the argument vector, followed by zero
# or more arguments to be given to OpenSCAD
SCAD_FILE="$($EXEC_FILE)"

if [[ "$SCAD_FILE" != /* ]]; then
    SCAD_FILE=$PWD/$SCAD_FILE
fi

if [ ! -f $SCAD_FILE ]; then
    echo "invalid file: $SCAD_FILE"
    exit 1
fi

openscad $SCAD_FILE
#openscad $OPENSCAD_ARGS $SCAD_FILE

exit 0
